url: https://tc.services
baseurl: /ukraine

# Site settings
title: Travel Concierge | Ukraine
email: your-email@domain.com
description: "We make you trip to Ukraine awesome!"


# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Emmerich
  - line: Germnay

# Build settings
markdown: kramdown
permalink: pretty