url: https://tc.services
baseurl: /

# Site settings
title: Travel Concierge | Ukraine
email: info@tc.services
description: "We make your trip to Ukraine awesome!"


# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/tc.servicesUA

# Postal address (add as many lines as necessary)
address:
  - line: Emmerich
  - line: Germnay

# Build settings
markdown: kramdown
permalink: pretty